/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as protectedAuthenticatedRouteImport } from './routes/(protected)/_authenticated'
import { Route as protectedAuthenticatedIndexRouteImport } from './routes/(protected)/_authenticated/index'
import { Route as protectedAuthenticatedPersonnelCvRouteImport } from './routes/(protected)/_authenticated/personnel-cv'
import { Route as protectedAuthenticatedPersonnelCvIndexRouteImport } from './routes/(protected)/_authenticated/personnel-cv/index'
import { Route as protectedAuthenticatedPersonnelCvWorkHistoryRouteImport } from './routes/(protected)/_authenticated/personnel-cv/work-history'
import { Route as protectedAuthenticatedPersonnelCvTrainingRouteImport } from './routes/(protected)/_authenticated/personnel-cv/training'
import { Route as protectedAuthenticatedPersonnelCvSalaryRouteImport } from './routes/(protected)/_authenticated/personnel-cv/salary'
import { Route as protectedAuthenticatedPersonnelCvRecruitmentRouteImport } from './routes/(protected)/_authenticated/personnel-cv/recruitment'
import { Route as protectedAuthenticatedPersonnelCvOtherRouteImport } from './routes/(protected)/_authenticated/personnel-cv/other'
import { Route as protectedAuthenticatedPersonnelCvHealthRouteImport } from './routes/(protected)/_authenticated/personnel-cv/health'
import { Route as protectedAuthenticatedPersonnelCvFamilyRouteImport } from './routes/(protected)/_authenticated/personnel-cv/family'
import { Route as protectedAuthenticatedPersonnelCvContractRouteImport } from './routes/(protected)/_authenticated/personnel-cv/contract'
import { Route as protectedAuthenticatedPersonnelCvAwardsAndDisciplinesRouteImport } from './routes/(protected)/_authenticated/personnel-cv/awards-and-disciplines'
import { Route as protectedAuthenticatedAcademicCvTrainingProductsRouteImport } from './routes/(protected)/_authenticated/academic-cv/training-products'
import { Route as protectedAuthenticatedAcademicCvScholarlyWorksRouteImport } from './routes/(protected)/_authenticated/academic-cv/scholarly-works'
import { Route as protectedAuthenticatedAcademicCvProjectsRouteImport } from './routes/(protected)/_authenticated/academic-cv/projects'
import { Route as protectedAuthenticatedAcademicCvPatentsRouteImport } from './routes/(protected)/_authenticated/academic-cv/patents'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedAuthenticatedRoute = protectedAuthenticatedRouteImport.update({
  id: '/(protected)/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedAuthenticatedIndexRoute =
  protectedAuthenticatedIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => protectedAuthenticatedRoute,
  } as any)
const protectedAuthenticatedPersonnelCvRoute =
  protectedAuthenticatedPersonnelCvRouteImport.update({
    id: '/personnel-cv',
    path: '/personnel-cv',
    getParentRoute: () => protectedAuthenticatedRoute,
  } as any)
const protectedAuthenticatedPersonnelCvIndexRoute =
  protectedAuthenticatedPersonnelCvIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => protectedAuthenticatedPersonnelCvRoute,
  } as any)
const protectedAuthenticatedPersonnelCvWorkHistoryRoute =
  protectedAuthenticatedPersonnelCvWorkHistoryRouteImport.update({
    id: '/work-history',
    path: '/work-history',
    getParentRoute: () => protectedAuthenticatedPersonnelCvRoute,
  } as any)
const protectedAuthenticatedPersonnelCvTrainingRoute =
  protectedAuthenticatedPersonnelCvTrainingRouteImport.update({
    id: '/training',
    path: '/training',
    getParentRoute: () => protectedAuthenticatedPersonnelCvRoute,
  } as any)
const protectedAuthenticatedPersonnelCvSalaryRoute =
  protectedAuthenticatedPersonnelCvSalaryRouteImport.update({
    id: '/salary',
    path: '/salary',
    getParentRoute: () => protectedAuthenticatedPersonnelCvRoute,
  } as any)
const protectedAuthenticatedPersonnelCvRecruitmentRoute =
  protectedAuthenticatedPersonnelCvRecruitmentRouteImport.update({
    id: '/recruitment',
    path: '/recruitment',
    getParentRoute: () => protectedAuthenticatedPersonnelCvRoute,
  } as any)
const protectedAuthenticatedPersonnelCvOtherRoute =
  protectedAuthenticatedPersonnelCvOtherRouteImport.update({
    id: '/other',
    path: '/other',
    getParentRoute: () => protectedAuthenticatedPersonnelCvRoute,
  } as any)
const protectedAuthenticatedPersonnelCvHealthRoute =
  protectedAuthenticatedPersonnelCvHealthRouteImport.update({
    id: '/health',
    path: '/health',
    getParentRoute: () => protectedAuthenticatedPersonnelCvRoute,
  } as any)
const protectedAuthenticatedPersonnelCvFamilyRoute =
  protectedAuthenticatedPersonnelCvFamilyRouteImport.update({
    id: '/family',
    path: '/family',
    getParentRoute: () => protectedAuthenticatedPersonnelCvRoute,
  } as any)
const protectedAuthenticatedPersonnelCvContractRoute =
  protectedAuthenticatedPersonnelCvContractRouteImport.update({
    id: '/contract',
    path: '/contract',
    getParentRoute: () => protectedAuthenticatedPersonnelCvRoute,
  } as any)
const protectedAuthenticatedPersonnelCvAwardsAndDisciplinesRoute =
  protectedAuthenticatedPersonnelCvAwardsAndDisciplinesRouteImport.update({
    id: '/awards-and-disciplines',
    path: '/awards-and-disciplines',
    getParentRoute: () => protectedAuthenticatedPersonnelCvRoute,
  } as any)
const protectedAuthenticatedAcademicCvTrainingProductsRoute =
  protectedAuthenticatedAcademicCvTrainingProductsRouteImport.update({
    id: '/academic-cv/training-products',
    path: '/academic-cv/training-products',
    getParentRoute: () => protectedAuthenticatedRoute,
  } as any)
const protectedAuthenticatedAcademicCvScholarlyWorksRoute =
  protectedAuthenticatedAcademicCvScholarlyWorksRouteImport.update({
    id: '/academic-cv/scholarly-works',
    path: '/academic-cv/scholarly-works',
    getParentRoute: () => protectedAuthenticatedRoute,
  } as any)
const protectedAuthenticatedAcademicCvProjectsRoute =
  protectedAuthenticatedAcademicCvProjectsRouteImport.update({
    id: '/academic-cv/projects',
    path: '/academic-cv/projects',
    getParentRoute: () => protectedAuthenticatedRoute,
  } as any)
const protectedAuthenticatedAcademicCvPatentsRoute =
  protectedAuthenticatedAcademicCvPatentsRouteImport.update({
    id: '/academic-cv/patents',
    path: '/academic-cv/patents',
    getParentRoute: () => protectedAuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/personnel-cv': typeof protectedAuthenticatedPersonnelCvRouteWithChildren
  '/': typeof protectedAuthenticatedIndexRoute
  '/academic-cv/patents': typeof protectedAuthenticatedAcademicCvPatentsRoute
  '/academic-cv/projects': typeof protectedAuthenticatedAcademicCvProjectsRoute
  '/academic-cv/scholarly-works': typeof protectedAuthenticatedAcademicCvScholarlyWorksRoute
  '/academic-cv/training-products': typeof protectedAuthenticatedAcademicCvTrainingProductsRoute
  '/personnel-cv/awards-and-disciplines': typeof protectedAuthenticatedPersonnelCvAwardsAndDisciplinesRoute
  '/personnel-cv/contract': typeof protectedAuthenticatedPersonnelCvContractRoute
  '/personnel-cv/family': typeof protectedAuthenticatedPersonnelCvFamilyRoute
  '/personnel-cv/health': typeof protectedAuthenticatedPersonnelCvHealthRoute
  '/personnel-cv/other': typeof protectedAuthenticatedPersonnelCvOtherRoute
  '/personnel-cv/recruitment': typeof protectedAuthenticatedPersonnelCvRecruitmentRoute
  '/personnel-cv/salary': typeof protectedAuthenticatedPersonnelCvSalaryRoute
  '/personnel-cv/training': typeof protectedAuthenticatedPersonnelCvTrainingRoute
  '/personnel-cv/work-history': typeof protectedAuthenticatedPersonnelCvWorkHistoryRoute
  '/personnel-cv/': typeof protectedAuthenticatedPersonnelCvIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof protectedAuthenticatedIndexRoute
  '/academic-cv/patents': typeof protectedAuthenticatedAcademicCvPatentsRoute
  '/academic-cv/projects': typeof protectedAuthenticatedAcademicCvProjectsRoute
  '/academic-cv/scholarly-works': typeof protectedAuthenticatedAcademicCvScholarlyWorksRoute
  '/academic-cv/training-products': typeof protectedAuthenticatedAcademicCvTrainingProductsRoute
  '/personnel-cv/awards-and-disciplines': typeof protectedAuthenticatedPersonnelCvAwardsAndDisciplinesRoute
  '/personnel-cv/contract': typeof protectedAuthenticatedPersonnelCvContractRoute
  '/personnel-cv/family': typeof protectedAuthenticatedPersonnelCvFamilyRoute
  '/personnel-cv/health': typeof protectedAuthenticatedPersonnelCvHealthRoute
  '/personnel-cv/other': typeof protectedAuthenticatedPersonnelCvOtherRoute
  '/personnel-cv/recruitment': typeof protectedAuthenticatedPersonnelCvRecruitmentRoute
  '/personnel-cv/salary': typeof protectedAuthenticatedPersonnelCvSalaryRoute
  '/personnel-cv/training': typeof protectedAuthenticatedPersonnelCvTrainingRoute
  '/personnel-cv/work-history': typeof protectedAuthenticatedPersonnelCvWorkHistoryRoute
  '/personnel-cv': typeof protectedAuthenticatedPersonnelCvIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/login': typeof LoginRoute
  '/(protected)/_authenticated': typeof protectedAuthenticatedRouteWithChildren
  '/(protected)/_authenticated/personnel-cv': typeof protectedAuthenticatedPersonnelCvRouteWithChildren
  '/(protected)/_authenticated/': typeof protectedAuthenticatedIndexRoute
  '/(protected)/_authenticated/academic-cv/patents': typeof protectedAuthenticatedAcademicCvPatentsRoute
  '/(protected)/_authenticated/academic-cv/projects': typeof protectedAuthenticatedAcademicCvProjectsRoute
  '/(protected)/_authenticated/academic-cv/scholarly-works': typeof protectedAuthenticatedAcademicCvScholarlyWorksRoute
  '/(protected)/_authenticated/academic-cv/training-products': typeof protectedAuthenticatedAcademicCvTrainingProductsRoute
  '/(protected)/_authenticated/personnel-cv/awards-and-disciplines': typeof protectedAuthenticatedPersonnelCvAwardsAndDisciplinesRoute
  '/(protected)/_authenticated/personnel-cv/contract': typeof protectedAuthenticatedPersonnelCvContractRoute
  '/(protected)/_authenticated/personnel-cv/family': typeof protectedAuthenticatedPersonnelCvFamilyRoute
  '/(protected)/_authenticated/personnel-cv/health': typeof protectedAuthenticatedPersonnelCvHealthRoute
  '/(protected)/_authenticated/personnel-cv/other': typeof protectedAuthenticatedPersonnelCvOtherRoute
  '/(protected)/_authenticated/personnel-cv/recruitment': typeof protectedAuthenticatedPersonnelCvRecruitmentRoute
  '/(protected)/_authenticated/personnel-cv/salary': typeof protectedAuthenticatedPersonnelCvSalaryRoute
  '/(protected)/_authenticated/personnel-cv/training': typeof protectedAuthenticatedPersonnelCvTrainingRoute
  '/(protected)/_authenticated/personnel-cv/work-history': typeof protectedAuthenticatedPersonnelCvWorkHistoryRoute
  '/(protected)/_authenticated/personnel-cv/': typeof protectedAuthenticatedPersonnelCvIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/personnel-cv'
    | '/'
    | '/academic-cv/patents'
    | '/academic-cv/projects'
    | '/academic-cv/scholarly-works'
    | '/academic-cv/training-products'
    | '/personnel-cv/awards-and-disciplines'
    | '/personnel-cv/contract'
    | '/personnel-cv/family'
    | '/personnel-cv/health'
    | '/personnel-cv/other'
    | '/personnel-cv/recruitment'
    | '/personnel-cv/salary'
    | '/personnel-cv/training'
    | '/personnel-cv/work-history'
    | '/personnel-cv/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/academic-cv/patents'
    | '/academic-cv/projects'
    | '/academic-cv/scholarly-works'
    | '/academic-cv/training-products'
    | '/personnel-cv/awards-and-disciplines'
    | '/personnel-cv/contract'
    | '/personnel-cv/family'
    | '/personnel-cv/health'
    | '/personnel-cv/other'
    | '/personnel-cv/recruitment'
    | '/personnel-cv/salary'
    | '/personnel-cv/training'
    | '/personnel-cv/work-history'
    | '/personnel-cv'
  id:
    | '__root__'
    | '/login'
    | '/(protected)/_authenticated'
    | '/(protected)/_authenticated/personnel-cv'
    | '/(protected)/_authenticated/'
    | '/(protected)/_authenticated/academic-cv/patents'
    | '/(protected)/_authenticated/academic-cv/projects'
    | '/(protected)/_authenticated/academic-cv/scholarly-works'
    | '/(protected)/_authenticated/academic-cv/training-products'
    | '/(protected)/_authenticated/personnel-cv/awards-and-disciplines'
    | '/(protected)/_authenticated/personnel-cv/contract'
    | '/(protected)/_authenticated/personnel-cv/family'
    | '/(protected)/_authenticated/personnel-cv/health'
    | '/(protected)/_authenticated/personnel-cv/other'
    | '/(protected)/_authenticated/personnel-cv/recruitment'
    | '/(protected)/_authenticated/personnel-cv/salary'
    | '/(protected)/_authenticated/personnel-cv/training'
    | '/(protected)/_authenticated/personnel-cv/work-history'
    | '/(protected)/_authenticated/personnel-cv/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LoginRoute: typeof LoginRoute
  protectedAuthenticatedRoute: typeof protectedAuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/_authenticated': {
      id: '/(protected)/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedAuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/_authenticated/': {
      id: '/(protected)/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof protectedAuthenticatedIndexRouteImport
      parentRoute: typeof protectedAuthenticatedRoute
    }
    '/(protected)/_authenticated/personnel-cv': {
      id: '/(protected)/_authenticated/personnel-cv'
      path: '/personnel-cv'
      fullPath: '/personnel-cv'
      preLoaderRoute: typeof protectedAuthenticatedPersonnelCvRouteImport
      parentRoute: typeof protectedAuthenticatedRoute
    }
    '/(protected)/_authenticated/personnel-cv/': {
      id: '/(protected)/_authenticated/personnel-cv/'
      path: '/'
      fullPath: '/personnel-cv/'
      preLoaderRoute: typeof protectedAuthenticatedPersonnelCvIndexRouteImport
      parentRoute: typeof protectedAuthenticatedPersonnelCvRoute
    }
    '/(protected)/_authenticated/personnel-cv/work-history': {
      id: '/(protected)/_authenticated/personnel-cv/work-history'
      path: '/work-history'
      fullPath: '/personnel-cv/work-history'
      preLoaderRoute: typeof protectedAuthenticatedPersonnelCvWorkHistoryRouteImport
      parentRoute: typeof protectedAuthenticatedPersonnelCvRoute
    }
    '/(protected)/_authenticated/personnel-cv/training': {
      id: '/(protected)/_authenticated/personnel-cv/training'
      path: '/training'
      fullPath: '/personnel-cv/training'
      preLoaderRoute: typeof protectedAuthenticatedPersonnelCvTrainingRouteImport
      parentRoute: typeof protectedAuthenticatedPersonnelCvRoute
    }
    '/(protected)/_authenticated/personnel-cv/salary': {
      id: '/(protected)/_authenticated/personnel-cv/salary'
      path: '/salary'
      fullPath: '/personnel-cv/salary'
      preLoaderRoute: typeof protectedAuthenticatedPersonnelCvSalaryRouteImport
      parentRoute: typeof protectedAuthenticatedPersonnelCvRoute
    }
    '/(protected)/_authenticated/personnel-cv/recruitment': {
      id: '/(protected)/_authenticated/personnel-cv/recruitment'
      path: '/recruitment'
      fullPath: '/personnel-cv/recruitment'
      preLoaderRoute: typeof protectedAuthenticatedPersonnelCvRecruitmentRouteImport
      parentRoute: typeof protectedAuthenticatedPersonnelCvRoute
    }
    '/(protected)/_authenticated/personnel-cv/other': {
      id: '/(protected)/_authenticated/personnel-cv/other'
      path: '/other'
      fullPath: '/personnel-cv/other'
      preLoaderRoute: typeof protectedAuthenticatedPersonnelCvOtherRouteImport
      parentRoute: typeof protectedAuthenticatedPersonnelCvRoute
    }
    '/(protected)/_authenticated/personnel-cv/health': {
      id: '/(protected)/_authenticated/personnel-cv/health'
      path: '/health'
      fullPath: '/personnel-cv/health'
      preLoaderRoute: typeof protectedAuthenticatedPersonnelCvHealthRouteImport
      parentRoute: typeof protectedAuthenticatedPersonnelCvRoute
    }
    '/(protected)/_authenticated/personnel-cv/family': {
      id: '/(protected)/_authenticated/personnel-cv/family'
      path: '/family'
      fullPath: '/personnel-cv/family'
      preLoaderRoute: typeof protectedAuthenticatedPersonnelCvFamilyRouteImport
      parentRoute: typeof protectedAuthenticatedPersonnelCvRoute
    }
    '/(protected)/_authenticated/personnel-cv/contract': {
      id: '/(protected)/_authenticated/personnel-cv/contract'
      path: '/contract'
      fullPath: '/personnel-cv/contract'
      preLoaderRoute: typeof protectedAuthenticatedPersonnelCvContractRouteImport
      parentRoute: typeof protectedAuthenticatedPersonnelCvRoute
    }
    '/(protected)/_authenticated/personnel-cv/awards-and-disciplines': {
      id: '/(protected)/_authenticated/personnel-cv/awards-and-disciplines'
      path: '/awards-and-disciplines'
      fullPath: '/personnel-cv/awards-and-disciplines'
      preLoaderRoute: typeof protectedAuthenticatedPersonnelCvAwardsAndDisciplinesRouteImport
      parentRoute: typeof protectedAuthenticatedPersonnelCvRoute
    }
    '/(protected)/_authenticated/academic-cv/training-products': {
      id: '/(protected)/_authenticated/academic-cv/training-products'
      path: '/academic-cv/training-products'
      fullPath: '/academic-cv/training-products'
      preLoaderRoute: typeof protectedAuthenticatedAcademicCvTrainingProductsRouteImport
      parentRoute: typeof protectedAuthenticatedRoute
    }
    '/(protected)/_authenticated/academic-cv/scholarly-works': {
      id: '/(protected)/_authenticated/academic-cv/scholarly-works'
      path: '/academic-cv/scholarly-works'
      fullPath: '/academic-cv/scholarly-works'
      preLoaderRoute: typeof protectedAuthenticatedAcademicCvScholarlyWorksRouteImport
      parentRoute: typeof protectedAuthenticatedRoute
    }
    '/(protected)/_authenticated/academic-cv/projects': {
      id: '/(protected)/_authenticated/academic-cv/projects'
      path: '/academic-cv/projects'
      fullPath: '/academic-cv/projects'
      preLoaderRoute: typeof protectedAuthenticatedAcademicCvProjectsRouteImport
      parentRoute: typeof protectedAuthenticatedRoute
    }
    '/(protected)/_authenticated/academic-cv/patents': {
      id: '/(protected)/_authenticated/academic-cv/patents'
      path: '/academic-cv/patents'
      fullPath: '/academic-cv/patents'
      preLoaderRoute: typeof protectedAuthenticatedAcademicCvPatentsRouteImport
      parentRoute: typeof protectedAuthenticatedRoute
    }
  }
}

interface protectedAuthenticatedPersonnelCvRouteChildren {
  protectedAuthenticatedPersonnelCvAwardsAndDisciplinesRoute: typeof protectedAuthenticatedPersonnelCvAwardsAndDisciplinesRoute
  protectedAuthenticatedPersonnelCvContractRoute: typeof protectedAuthenticatedPersonnelCvContractRoute
  protectedAuthenticatedPersonnelCvFamilyRoute: typeof protectedAuthenticatedPersonnelCvFamilyRoute
  protectedAuthenticatedPersonnelCvHealthRoute: typeof protectedAuthenticatedPersonnelCvHealthRoute
  protectedAuthenticatedPersonnelCvOtherRoute: typeof protectedAuthenticatedPersonnelCvOtherRoute
  protectedAuthenticatedPersonnelCvRecruitmentRoute: typeof protectedAuthenticatedPersonnelCvRecruitmentRoute
  protectedAuthenticatedPersonnelCvSalaryRoute: typeof protectedAuthenticatedPersonnelCvSalaryRoute
  protectedAuthenticatedPersonnelCvTrainingRoute: typeof protectedAuthenticatedPersonnelCvTrainingRoute
  protectedAuthenticatedPersonnelCvWorkHistoryRoute: typeof protectedAuthenticatedPersonnelCvWorkHistoryRoute
  protectedAuthenticatedPersonnelCvIndexRoute: typeof protectedAuthenticatedPersonnelCvIndexRoute
}

const protectedAuthenticatedPersonnelCvRouteChildren: protectedAuthenticatedPersonnelCvRouteChildren =
  {
    protectedAuthenticatedPersonnelCvAwardsAndDisciplinesRoute:
      protectedAuthenticatedPersonnelCvAwardsAndDisciplinesRoute,
    protectedAuthenticatedPersonnelCvContractRoute:
      protectedAuthenticatedPersonnelCvContractRoute,
    protectedAuthenticatedPersonnelCvFamilyRoute:
      protectedAuthenticatedPersonnelCvFamilyRoute,
    protectedAuthenticatedPersonnelCvHealthRoute:
      protectedAuthenticatedPersonnelCvHealthRoute,
    protectedAuthenticatedPersonnelCvOtherRoute:
      protectedAuthenticatedPersonnelCvOtherRoute,
    protectedAuthenticatedPersonnelCvRecruitmentRoute:
      protectedAuthenticatedPersonnelCvRecruitmentRoute,
    protectedAuthenticatedPersonnelCvSalaryRoute:
      protectedAuthenticatedPersonnelCvSalaryRoute,
    protectedAuthenticatedPersonnelCvTrainingRoute:
      protectedAuthenticatedPersonnelCvTrainingRoute,
    protectedAuthenticatedPersonnelCvWorkHistoryRoute:
      protectedAuthenticatedPersonnelCvWorkHistoryRoute,
    protectedAuthenticatedPersonnelCvIndexRoute:
      protectedAuthenticatedPersonnelCvIndexRoute,
  }

const protectedAuthenticatedPersonnelCvRouteWithChildren =
  protectedAuthenticatedPersonnelCvRoute._addFileChildren(
    protectedAuthenticatedPersonnelCvRouteChildren,
  )

interface protectedAuthenticatedRouteChildren {
  protectedAuthenticatedPersonnelCvRoute: typeof protectedAuthenticatedPersonnelCvRouteWithChildren
  protectedAuthenticatedIndexRoute: typeof protectedAuthenticatedIndexRoute
  protectedAuthenticatedAcademicCvPatentsRoute: typeof protectedAuthenticatedAcademicCvPatentsRoute
  protectedAuthenticatedAcademicCvProjectsRoute: typeof protectedAuthenticatedAcademicCvProjectsRoute
  protectedAuthenticatedAcademicCvScholarlyWorksRoute: typeof protectedAuthenticatedAcademicCvScholarlyWorksRoute
  protectedAuthenticatedAcademicCvTrainingProductsRoute: typeof protectedAuthenticatedAcademicCvTrainingProductsRoute
}

const protectedAuthenticatedRouteChildren: protectedAuthenticatedRouteChildren =
  {
    protectedAuthenticatedPersonnelCvRoute:
      protectedAuthenticatedPersonnelCvRouteWithChildren,
    protectedAuthenticatedIndexRoute: protectedAuthenticatedIndexRoute,
    protectedAuthenticatedAcademicCvPatentsRoute:
      protectedAuthenticatedAcademicCvPatentsRoute,
    protectedAuthenticatedAcademicCvProjectsRoute:
      protectedAuthenticatedAcademicCvProjectsRoute,
    protectedAuthenticatedAcademicCvScholarlyWorksRoute:
      protectedAuthenticatedAcademicCvScholarlyWorksRoute,
    protectedAuthenticatedAcademicCvTrainingProductsRoute:
      protectedAuthenticatedAcademicCvTrainingProductsRoute,
  }

const protectedAuthenticatedRouteWithChildren =
  protectedAuthenticatedRoute._addFileChildren(
    protectedAuthenticatedRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  LoginRoute: LoginRoute,
  protectedAuthenticatedRoute: protectedAuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
