/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as protectedAuthenticatedRouteImport } from './routes/(protected)/_authenticated'
import { Route as protectedAuthenticatedIndexRouteImport } from './routes/(protected)/_authenticated/index'
import { Route as protectedAuthenticatedPersonnelCvRouteImport } from './routes/(protected)/_authenticated/personnel-cv'
import { Route as protectedAuthenticatedPersonnelCvHealthRouteImport } from './routes/(protected)/_authenticated/personnel-cv/health'
import { Route as protectedAuthenticatedPersonnelCvAwardsAndDisciplinesRouteImport } from './routes/(protected)/_authenticated/personnel-cv/awards-and-disciplines'
import { Route as protectedAuthenticatedAcademicCvScholarlyWorksRouteImport } from './routes/(protected)/_authenticated/academic-cv/scholarly-works'
import { Route as protectedAuthenticatedAcademicCvProjectsRouteImport } from './routes/(protected)/_authenticated/academic-cv/projects'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedAuthenticatedRoute = protectedAuthenticatedRouteImport.update({
  id: '/(protected)/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedAuthenticatedIndexRoute =
  protectedAuthenticatedIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => protectedAuthenticatedRoute,
  } as any)
const protectedAuthenticatedPersonnelCvRoute =
  protectedAuthenticatedPersonnelCvRouteImport.update({
    id: '/personnel-cv',
    path: '/personnel-cv',
    getParentRoute: () => protectedAuthenticatedRoute,
  } as any)
const protectedAuthenticatedPersonnelCvHealthRoute =
  protectedAuthenticatedPersonnelCvHealthRouteImport.update({
    id: '/health',
    path: '/health',
    getParentRoute: () => protectedAuthenticatedPersonnelCvRoute,
  } as any)
const protectedAuthenticatedPersonnelCvAwardsAndDisciplinesRoute =
  protectedAuthenticatedPersonnelCvAwardsAndDisciplinesRouteImport.update({
    id: '/awards-and-disciplines',
    path: '/awards-and-disciplines',
    getParentRoute: () => protectedAuthenticatedPersonnelCvRoute,
  } as any)
const protectedAuthenticatedAcademicCvScholarlyWorksRoute =
  protectedAuthenticatedAcademicCvScholarlyWorksRouteImport.update({
    id: '/academic-cv/scholarly-works',
    path: '/academic-cv/scholarly-works',
    getParentRoute: () => protectedAuthenticatedRoute,
  } as any)
const protectedAuthenticatedAcademicCvProjectsRoute =
  protectedAuthenticatedAcademicCvProjectsRouteImport.update({
    id: '/academic-cv/projects',
    path: '/academic-cv/projects',
    getParentRoute: () => protectedAuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/personnel-cv': typeof protectedAuthenticatedPersonnelCvRouteWithChildren
  '/': typeof protectedAuthenticatedIndexRoute
  '/academic-cv/projects': typeof protectedAuthenticatedAcademicCvProjectsRoute
  '/academic-cv/scholarly-works': typeof protectedAuthenticatedAcademicCvScholarlyWorksRoute
  '/personnel-cv/awards-and-disciplines': typeof protectedAuthenticatedPersonnelCvAwardsAndDisciplinesRoute
  '/personnel-cv/health': typeof protectedAuthenticatedPersonnelCvHealthRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/personnel-cv': typeof protectedAuthenticatedPersonnelCvRouteWithChildren
  '/': typeof protectedAuthenticatedIndexRoute
  '/academic-cv/projects': typeof protectedAuthenticatedAcademicCvProjectsRoute
  '/academic-cv/scholarly-works': typeof protectedAuthenticatedAcademicCvScholarlyWorksRoute
  '/personnel-cv/awards-and-disciplines': typeof protectedAuthenticatedPersonnelCvAwardsAndDisciplinesRoute
  '/personnel-cv/health': typeof protectedAuthenticatedPersonnelCvHealthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/login': typeof LoginRoute
  '/(protected)/_authenticated': typeof protectedAuthenticatedRouteWithChildren
  '/(protected)/_authenticated/personnel-cv': typeof protectedAuthenticatedPersonnelCvRouteWithChildren
  '/(protected)/_authenticated/': typeof protectedAuthenticatedIndexRoute
  '/(protected)/_authenticated/academic-cv/projects': typeof protectedAuthenticatedAcademicCvProjectsRoute
  '/(protected)/_authenticated/academic-cv/scholarly-works': typeof protectedAuthenticatedAcademicCvScholarlyWorksRoute
  '/(protected)/_authenticated/personnel-cv/awards-and-disciplines': typeof protectedAuthenticatedPersonnelCvAwardsAndDisciplinesRoute
  '/(protected)/_authenticated/personnel-cv/health': typeof protectedAuthenticatedPersonnelCvHealthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/personnel-cv'
    | '/'
    | '/academic-cv/projects'
    | '/academic-cv/scholarly-works'
    | '/personnel-cv/awards-and-disciplines'
    | '/personnel-cv/health'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/personnel-cv'
    | '/'
    | '/academic-cv/projects'
    | '/academic-cv/scholarly-works'
    | '/personnel-cv/awards-and-disciplines'
    | '/personnel-cv/health'
  id:
    | '__root__'
    | '/login'
    | '/(protected)/_authenticated'
    | '/(protected)/_authenticated/personnel-cv'
    | '/(protected)/_authenticated/'
    | '/(protected)/_authenticated/academic-cv/projects'
    | '/(protected)/_authenticated/academic-cv/scholarly-works'
    | '/(protected)/_authenticated/personnel-cv/awards-and-disciplines'
    | '/(protected)/_authenticated/personnel-cv/health'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LoginRoute: typeof LoginRoute
  protectedAuthenticatedRoute: typeof protectedAuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/_authenticated': {
      id: '/(protected)/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedAuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/_authenticated/': {
      id: '/(protected)/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof protectedAuthenticatedIndexRouteImport
      parentRoute: typeof protectedAuthenticatedRoute
    }
    '/(protected)/_authenticated/personnel-cv': {
      id: '/(protected)/_authenticated/personnel-cv'
      path: '/personnel-cv'
      fullPath: '/personnel-cv'
      preLoaderRoute: typeof protectedAuthenticatedPersonnelCvRouteImport
      parentRoute: typeof protectedAuthenticatedRoute
    }
    '/(protected)/_authenticated/personnel-cv/health': {
      id: '/(protected)/_authenticated/personnel-cv/health'
      path: '/health'
      fullPath: '/personnel-cv/health'
      preLoaderRoute: typeof protectedAuthenticatedPersonnelCvHealthRouteImport
      parentRoute: typeof protectedAuthenticatedPersonnelCvRoute
    }
    '/(protected)/_authenticated/personnel-cv/awards-and-disciplines': {
      id: '/(protected)/_authenticated/personnel-cv/awards-and-disciplines'
      path: '/awards-and-disciplines'
      fullPath: '/personnel-cv/awards-and-disciplines'
      preLoaderRoute: typeof protectedAuthenticatedPersonnelCvAwardsAndDisciplinesRouteImport
      parentRoute: typeof protectedAuthenticatedPersonnelCvRoute
    }
    '/(protected)/_authenticated/academic-cv/scholarly-works': {
      id: '/(protected)/_authenticated/academic-cv/scholarly-works'
      path: '/academic-cv/scholarly-works'
      fullPath: '/academic-cv/scholarly-works'
      preLoaderRoute: typeof protectedAuthenticatedAcademicCvScholarlyWorksRouteImport
      parentRoute: typeof protectedAuthenticatedRoute
    }
    '/(protected)/_authenticated/academic-cv/projects': {
      id: '/(protected)/_authenticated/academic-cv/projects'
      path: '/academic-cv/projects'
      fullPath: '/academic-cv/projects'
      preLoaderRoute: typeof protectedAuthenticatedAcademicCvProjectsRouteImport
      parentRoute: typeof protectedAuthenticatedRoute
    }
  }
}

interface protectedAuthenticatedPersonnelCvRouteChildren {
  protectedAuthenticatedPersonnelCvAwardsAndDisciplinesRoute: typeof protectedAuthenticatedPersonnelCvAwardsAndDisciplinesRoute
  protectedAuthenticatedPersonnelCvHealthRoute: typeof protectedAuthenticatedPersonnelCvHealthRoute
}

const protectedAuthenticatedPersonnelCvRouteChildren: protectedAuthenticatedPersonnelCvRouteChildren =
  {
    protectedAuthenticatedPersonnelCvAwardsAndDisciplinesRoute:
      protectedAuthenticatedPersonnelCvAwardsAndDisciplinesRoute,
    protectedAuthenticatedPersonnelCvHealthRoute:
      protectedAuthenticatedPersonnelCvHealthRoute,
  }

const protectedAuthenticatedPersonnelCvRouteWithChildren =
  protectedAuthenticatedPersonnelCvRoute._addFileChildren(
    protectedAuthenticatedPersonnelCvRouteChildren,
  )

interface protectedAuthenticatedRouteChildren {
  protectedAuthenticatedPersonnelCvRoute: typeof protectedAuthenticatedPersonnelCvRouteWithChildren
  protectedAuthenticatedIndexRoute: typeof protectedAuthenticatedIndexRoute
  protectedAuthenticatedAcademicCvProjectsRoute: typeof protectedAuthenticatedAcademicCvProjectsRoute
  protectedAuthenticatedAcademicCvScholarlyWorksRoute: typeof protectedAuthenticatedAcademicCvScholarlyWorksRoute
}

const protectedAuthenticatedRouteChildren: protectedAuthenticatedRouteChildren =
  {
    protectedAuthenticatedPersonnelCvRoute:
      protectedAuthenticatedPersonnelCvRouteWithChildren,
    protectedAuthenticatedIndexRoute: protectedAuthenticatedIndexRoute,
    protectedAuthenticatedAcademicCvProjectsRoute:
      protectedAuthenticatedAcademicCvProjectsRoute,
    protectedAuthenticatedAcademicCvScholarlyWorksRoute:
      protectedAuthenticatedAcademicCvScholarlyWorksRoute,
  }

const protectedAuthenticatedRouteWithChildren =
  protectedAuthenticatedRoute._addFileChildren(
    protectedAuthenticatedRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  LoginRoute: LoginRoute,
  protectedAuthenticatedRoute: protectedAuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
